// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ReactDOMRe from "reason-react/src/ReactDOMRe.js";
import * as Component1$Codexmk2 from "./Component1.bs.js";
import * as Component2$Codexmk2 from "./Component2.bs.js";

ReactDOMRe.renderToElementWithId(React.createElement(Component1$Codexmk2.make, {
          message: "Hello! Click this text."
        }), "index1");

ReactDOMRe.renderToElementWithId(React.createElement(Component2$Codexmk2.make, {
          greeting: "Hello!"
        }), "index2");

export {
  
}
/*  Not a pure module */
